$(function(){function m(a,b){0<$(".welcome").length&&($(".stats li."+a+" span").html(b),$(".stats li."+a+" .spinner ").fadeOut(250,function(){$(this).remove();$(".stats li."+a).removeClass("disabled")}))}function p(){$(".timeline-cover").animate({opacity:1,bottom:"23px"},250);$(".welcome, .backdrop").fadeIn(250,function(){$(".nav .input_field").fadeOut(250,function(){$(".filter-help").animate({top:"0",opacity:1},250)});$(".left-side").animate({left:"0",opacity:1},400);$(".right-side").animate({left:"0",
opacity:1},400)})}function n(){var a=$(".input_field input#lat").val(),b=$(".input_field input#lng").val();a&&b&&o(function(){var d=new google.maps.LatLng(a,b);g.panTo(d);g.setZoom(7);$("#addresspicker").val("");$(".input_field .placeholder").show()})}function o(a){var b=function(){a&&a()},d=function(){$(".welcome, .backdrop").fadeOut(250,b);$(".nav .input_field").fadeIn(550)};$(".timeline-cover").animate({opacity:0,bottom:-30},250,function(){$(".filter-help").animate({top:"-100px",opacity:0},250);
$(".left-side").animate({left:"-200px",opacity:0},400);$(".right-side").animate({left:"200px",opacity:0},400,d);$(".pac-container").fadeOut(250)})}function k(a){a.addClass("loading");a=document.getElementById(a.attr("id"));a=(new Spinner({lines:7,length:0,width:3,radius:4,rotate:0,color:"#000",speed:1,trail:55,shadow:!1,hwaccel:!1,zIndex:2E9,left:-22,top:0})).spin(a);$(a.el).fadeIn(250)}var q=[];$(document).on("click",function(){$(".nav a[data-toggle='filter']").hasClass("selected")&&($(".nav a[data-toggle='filter']").removeClass("selected"),
$(".nav .filter").fadeOut(150))});$("a[data-click='search']").on("click",function(a){a.preventDefault();Aside.show("search")});$("a[data-click='explore']").on("click",function(a){a.preventDefault();o()});$("a[data-click='visit']").on("click",function(a){a.preventDefault();n()});$("a[data-click='welcome']").on("click",function(a){a.preventDefault();p()});var h=new google.maps.LatLngBounds(new google.maps.LatLng(13.39029,-26.33247),new google.maps.LatLng(-59.450451,-109.47493));$("#addresspicker").geocomplete({details:".input_field",
detailsAttribute:"data-geo",bounds:h});$("ul.stats li").each(function(a,b){var d=null,c=$(b),d="spinner_"+c.attr("class");c.append('<div id="'+d+'" class="spinner"></div>');d=document.getElementById(d);(new Spinner(config.BIG_SPINNER_OPTIONS)).spin(d);c.find(".spinner").fadeIn(250)});$(".input_field").smartPlaceholder();$("#addresspicker").keydown(function(a){13===a.keyCode&&(a.preventDefault(),n())});0>=$("ul.radio li.selected").length&&$("ul.radio li:first-child").addClass("selected");$(".nav a[data-toggle='filter']").on("click",
function(a){a.preventDefault();a.stopPropagation();$(".nav a[data-toggle='filter'].selected").not(this).removeClass("selected");$(this).toggleClass("selected");$(".nav a[data-toggle='filter']").not(this).parent().find(".filter").fadeOut(250);$(this).parent().find(".filter").fadeToggle(150)});$(".nav .filter ul.radio li").on("click",function(a){a.preventDefault();a.stopPropagation();$(this).parent().find("li").each(function(){$(this).attr("id")});$(this).parent().find("li").removeClass("selected");
$(this).addClass("selected")});$(".nav .filter").on("click",function(a){a.preventDefault();a.stopPropagation()});var r=function(){function a(){$(window).mousemove(function(a){r.positionate(a.pageX+10,a.pageY+10)});$(window).mouseleave(function(){$(b).css("opacity",0)});$(window).mouseenter(function(){$(b).css("opacity",1)})}var b;b=document.getElementById("minispinner_wrapper");(new Spinner({lines:7,length:0,width:3,radius:4,rotate:0,color:"#000",speed:1,trail:55,shadow:!1,hwaccel:!1,className:"spinner",
zIndex:2E9,top:"auto",left:"auto"})).spin(b);return{show:function(){$(b).fadeIn();a()},hide:function(){$(b).fadeOut(function(){$(window).unbind("mousemove mouseleave mouseenter")})},positionate:function(a,c){$(b).css({top:c+"px",left:a+"px"})}}}();$(document).keyup(function(a){27===a.keyCode&&(Infowindow.hide(),$(".nav .filter").fadeOut(150))});Aside=function(){var a=$(".aside"),b=$(".aside a.close"),d=0;(function(){b.on("click",function(a){a.preventDefault();0===d?($(this).data("project").unMarkSelected(!0),
$(this).removeData("project"),g.setZoom(previousZoom),Aside.hide(Timeline.show)):Aside.hide()})})();_show=function(c){"project"===c?(d=0,a.find(".search").hide(),a.find(".project").show()):(d=1,a.find(".project").hide(),a.find(".search").show());(c=b.data("project"))&&c.unMarkSelected(!0);a.find("li").css({opacity:0,marginLeft:150});$("#map").animate({right:"352px"},250);a.animate({right:0},250,function(){$(this).removeClass("hidden");$(this).find("li").each(function(a,b){$(b).delay(a*120).animate({marginLeft:0,
opacity:1},200)})})};_hide=function(b){$("#map").animate({right:"0"},250);a.animate({right:"-400px"},250,function(){$(this).addClass("hidden");b&&b()})};_isHidden=function(){return a.hasClass("hidden")};return{hide:_hide,show:_show,isHidden:_isHidden}}();Timeline=function(){_show=function(){Aside.isHidden()&&$("#timeline").animate({bottom:19,opacity:1},300)};_hide=function(a){$("#timeline").animate({bottom:-90,opacity:0},250,function(){a&&a()})};return{hide:_hide,show:_show}}();$("#timeline .slider").slider({range:!0,
min:0,max:390,step:30,values:[0,500],stop:function(){mapView.startYear=config.START_YEAR;mapView.endYear=config.END_YEAR;mapView.removeOverlay("projects");mapView.addProjects()},slide:function(a,b){$("#timeline li").removeClass("selected");var d=b.values[0]/30+1,c=b.values[1]/30;startYear=config.YEARS[d-1];for(endYear=config.YEARS[c-1];d<=c;d++)$("#timeline li:nth-child("+d+")").addClass("selected")}});var h={zoom:config.ZOOM,minZoom:config.MINZOOM,maxZoom:config.MAXZOOM,center:new google.maps.LatLng(config.LAT,
config.LNG),mapTypeId:google.maps.MapTypeId.ROADMAP,disableDefaultUI:!0},g=new google.maps.Map(document.getElementById("map"),h),h=document.getElementById("zoom_controls"),e=document.createElement("DIV");h.appendChild(e);new function(a,b){a.setAttribute("class","zoom_in");google.maps.event.addDomListener(a,"mousedown",function(){var a=b.getZoom()+1;20>a&&b.setZoom(a)})}(e,g);e.index=1;e=document.createElement("DIV");h.appendChild(e);new function(a,b){a.setAttribute("class","zoom_out");google.maps.event.addDomListener(a,
"mousedown",function(){var a=b.getZoom()-1;2<a&&b.setZoom(a)})}(e,g);e.index=2;g.mapTypes.set("nexsoStyle",nexsoStyle);g.setMapTypeId("nexsoStyle");google.maps.event.addListener(g,"zoom_changed",function(){Infowindow.hide();$(".stations").css({width:$(document).width(),height:$(document).height(),top:0,left:0})});Infowindow=new InfoWindow({map:g});var e=Backbone.CartoDB({user:config.CARTODB_USER}),j=e.CartoDBModel.extend({topic_id:function(){return this.get("topic_id")},name:function(){return this.get("name")},
lat:function(){return!this.get("location")?0:this.get("location").coordinates[1]},lng:function(){return!this.get("location")?0:this.get("location").coordinates[0]}}),h=e.CartoDBCollection.extend({model:j,table:"v1_ashoka",columns:{name:"name",location:"the_geom",topic_id:"topic_id"}}),j=e.CartoDBCollection.extend({model:j,table:"v1_agencies",columns:{name:"name",location:"the_geom"}}),e=Backbone.View.extend({events:{},initialize:function(){this.state=1;this.overlays=[];this.circles=[];this.coordinates=
[];this.addAgencies();this.addAshokas();this.addProjects()},enableFilters:function(){disabledFilters&&(disabledFilters=!1,$(".nav .spinner").fadeOut(250,function(){$(this).parent().removeClass("loading");$(this).remove()}))},disableFilters:function(){disabledFilters||(disabledFilters=!0)},removeOverlay:function(a){"ashokas"===a||"agencies"===a?this.removeMarkers(a):"projects"===a&&this.removeProjects(a)},removeMarkers:function(a){for(var b=0;b<this.overlays[a].length;b++)this.overlays[a][b].hide(!0);
this.enableFilters()},removeProjects:function(a){if(0<this.circles.length)for(var b=0;b<this.circles.length;b++)this.circles[b].circle.setMap(null);if(this.overlays[a].length)for(b=0;b<this.overlays[a].length;b++)if(this.overlays[a][b].length)for(var d=0;d<this.overlays[a][b].length;d++)this.overlays[a][b][d][0].setMap(null);this.enableFilters()},changeOpacity:function(a,b){_.each(mapView.overlays[a],function(a){a.changeOpacity(b)})},hideOverlay:function(a){_.each(mapView.overlays[a],function(a){a.hide(!0)})},
addAshokas:function(){this.disableFilters();this.overlays.ashokas?(_.each(this.overlays.ashokas,function(a){("solutions"===solutionFilter&&a.properties.solution_id||"all"===solutionFilter)&&_.include(topics,a.properties.topic_id)?a.show(!0):a.hide(!0)}),this.enableFilters()):this.addOverlay("ashokas",queries.GET_ASHOKAS)},addAgencies:function(){this.disableFilters();this.overlays.agencies?(_.each(this.overlays.agencies,function(a){("solutions"===solutionFilter&&a.properties.solution_id||"all"===solutionFilter)&&
_.include(topics,a.properties.topic_id)?a.show(!0):a.hide(!0)}),this.enableFilters()):this.addOverlay("agencies",queries.GET_AGENCIES)},addProjects:function(){this.disableFilters();this.startYear||(this.startYear=config.START_YEAR);this.endYear||(this.endYear=config.END_YEAR);var a=0<topics.length?" P.topic_id  IN ("+topics.join(",")+") AND ":"",b="solutions"===solutionFilter?" P.solution_id IS NOT NULL AND ":"";this.addOverlay("projects",_.template(queries.GET_PROJECTS_QUERY_TEMPLATE)({startYear:this.startYear,
endYear:this.endYear,topicsCondition:a,solutionCondition:b}),function(){Timeline.show()})},addOverlay:function(a,b,d){var c=this;this.disableFilters();$.ajax({url:config.CARTODB_ENDPOINT,data:{q:b,format:"geojson"},dataType:"jsonp",success:function(b){if(0>=b.features.length)c.enableFilters();else{m(a,b.features.length);var e=projectsStyle,f=null;try{f=JSON.parse(b)}catch(h){f=b}b=$.extend({},e);c.overlays[a]=new GeoJSON(f,a,b||null);if(!(c.overlays[a].type&&"Error"===c.overlays[a].type)){b=[];l=
[];solution_count=0;if(c.overlays[a].length)for(f=0;f<c.overlays[a].length;f++)if(c.overlays[a][f].length){b=[];l=[];for(e=0;e<c.overlays[a][f].length;e++){var i=c.overlays[a][f][e][0];i.setMap(g);b.push(i);c.coordinates[i.geojsonProperties.project_id]=[c.overlays[a][f][0][0].geojsonProperties.centroid_lat,c.overlays[a][f][0][0].geojsonProperties.centroid_lon]}b=c.overlays[a][f][0][0].geojsonProperties;e=new google.maps.LatLng(b.centroid_lat,b.centroid_lon);i=new google.maps.LatLng(b.radius_point_lat,
b.radius_point_lon);e=new RadiusWidget(g,e,i,c.overlays[a][f],[b.agency_position]);"projects"===a&&q.push({circle:e.circle,more:b,value:b.title,lat:b.centroid_lat,lng:b.centroid_lon});c.circles.push(e);"projects"===a&&(solution_count+=b.solution_count)}else c.overlays[a][f].setMap(g);"projects"===a&&m("solutions",solution_count)}c.enableFilters();d&&d()}}})}}),l=new j,h=new h;mapView=new e({el:$("#map"),ashoka:h,agencies:l});filterView=new (Backbone.View.extend({initialize:function(){var a=this;this.$("#solution-filter li").on("click",
function(b){b.preventDefault();b.stopPropagation();a.filterBySolution($(this))});this.$("#topic-filter li").on("click",function(b){b.preventDefault();b.stopPropagation();a.filterByTopic($(this))});this.$("#type-filter li").on("click",function(b){b.preventDefault();b.stopPropagation();a.filterByType($(this))})},disable:function(){$(".cancel").on("click",function(a){a.preventDefault();a.stopPropagation()});$("ul.filters").addClass("disabled");$(".cancel").show()},enable:function(){$("ul.filters").removeClass("disabled");
$(".cancel").hide()},filterByTopic:function(a){if(!disabledFilters){mapView.disableFilters();k(a);a.toggleClass("selected");a.attr("id").trim();var b=parseInt(a.attr("class").replace(/selected/,"").replace("t","").trim(),10);a.hasClass("selected")?topics.push(b):topics=_.without(topics,b);0<topics.length?($("#projects").addClass("selected"),mapView.removeOverlay("projects"),mapView.addProjects(),mapView.addAgencies(),mapView.addAshokas()):(mapView.removeOverlay("projects"),mapView.removeOverlay("agencies"),
mapView.removeOverlay("ashokas"))}},filterBySolution:function(a){disabledFilters||(mapView.disableFilters(),k(a),solutionFilter=a.attr("id").trim(),mapView.removeOverlay("projects"),mapView.addProjects(),mapView.addAgencies(),mapView.addAshokas())},filterByType:function(a){if(!disabledFilters){mapView.disableFilters();k(a);a.toggleClass("selected");var b=a.attr("id").trim();a.attr("class").replace(/selected/,"").trim();if(a.hasClass("selected"))"agencies"===b?mapView.addAgencies():"ashokas"===b?mapView.addAshokas():
"projects"===b&&mapView.addProjects();else if("projects"===b||"agencies"===b||"ashokas"===b)"projects"===b&&Timeline.hide(),Infowindow.hide(),mapView.removeOverlay(b)}}}))({el:$(".nav .content")})});
